apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  mapserver
  
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    minSize: 3
    maxSize: 5 
    volumeSize: 80
     
